PRAGMA foreign_keys = ON;

CREATE TABLE users(
  username VARCHAR(20) NOT NULL,
  fullname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  filename VARCHAR(64) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY(username)
);

CREATE TABLE posts(
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  postid INTEGER PRIMARY KEY AUTOINCREMENT,
  filename VARCHAR(64) NOT NULL,
  owner VARCHAR(20) NOT NULL,
  FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE
);

CREATE TABLE following(
  username1 VARCHAR(20) NOT NULL,
  username2 VARCHAR(20) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (username1, username2),
  FOREIGN KEY (username1) REFERENCES users(username) ON DELETE CASCADE,
  FOREIGN KEY (username2) REFERENCES users(username) ON DELETE CASCADE
);

CREATE TABLE comments(
  created DATETIME DEFAULT CURRENT_TIMESTAMP, 
  commentid INTEGER PRIMARY KEY AUTOINCREMENT,
  owner VARCHAR(20) NOT NULL,
  postid INTEGER NOT NULL, 
  text VARCHAR(1024) NOT NULL,
  FOREIGN KEY (postid) REFERENCES posts(postid) ON DELETE CASCADE,
  FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE
);

CREATE TABLE likes(
  created DATETIME DEFAULT CURRENT_TIMESTAMP, 
  likeid INTEGER PRIMARY KEY AUTOINCREMENT,
  postid INTEGER NOT NULL, 
  owner VARCHAR(20) NOT NULL,  -- Add this line to fix the error
  FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE,
  FOREIGN KEY (postid) REFERENCES posts(postid) ON DELETE CASCADE
);
